title: Anagha Kulkarni
description: Personal Webpage
sourcecode: "https://github.com/AnaghaK/anaghak.github.io"

permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

url: "https://anaghak.github.io"     # the base hostname & protocol for your site
baseurl: "/anaghak.github.io"                   # the subpath of your site, e.g. /blog

author:
    name:
    facebook:
    scholar:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
